name: binder-env
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - cuml-cpu=23.10
  - rdkit=2025.3.2
  - scikit-learn=1.4.2  # Installed via conda (mamba will handle this)
  - pip
  - pip:
      - jupyter==1.1.1
      - jupyterlab==4.4.3
      - pycaret==3.3.2
      - seaborn==0.13.2
      - pubchempy==1.0.4
      - joblib==1.3.2